### ISSUE TITLE
Scalastyle

### ISSUE THREAD

**Issue by catena2w** [input-output-hk/scrypto#34]
Add scalastyle plugin, configure jenkins to check style after commits

**Comment by SabaunT** [comment]
Currently I'm working on Windows 10 x64. I tried to test functions from  /functions lib.

An example:
`const {getUTXOlist} = require("./functions/getUTXOlist");

(async function () {
    await getUTXOlist("0x832a630B949575b87C0E3C00f624f773D9B160f4", "plasma-testnet.thematter.io/api/v1")
})();`
or like this (handling the promise):
`const {getUTXOlist} = require("./functions/getUTXOlist");

getUTXOlist("0x832a630B949575b87C0E3C00f624f773D9B160f4", "plasma-testnet.thematter.io/api/v1")
.then( (res) => console.log(res))
.catch(err => console.log(err))`

but both failed with a *status code error (404) * . The same was for that method:

`const {getLastWrittenBlock} = require("./functions/getLastWrittenBlock");

getLastWrittenBlock("plasma-testnet.thematter.io/api/v1").catch(err => console.log(err));`

I tried to deal with it using PlasmaWebUI starting a server on `localhost:3000`, but there were same problems. 


So, calling these methods with a node.js as a code processor returns this:
{ StatusCodeError: 404 - "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (C:\Users\Сабаун\Documents\PlasmaManager-master\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\Сабаун\Documents\PlasmaManager-master\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\Сабаун\Documents\PlasmaManager-master\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\Сабаун\Documents\PlasmaManager-master\node_modules\request\request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (C:\Users\Сабаун\Documents\PlasmaManager-master\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (C:\Users\Сабаун\Documents\PlasmaManager-master\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - "<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body bgcolor=\\"white\\">\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n"',
  error: '<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n',
  options:
   { method: 'GET',
     uri: 'http://plasma-testnet.thematter.io/api/v1/lastWrittenBlock',
     timeout: 30000,
     json: true,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [BufferList],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'plasma-testnet.thematter.io',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'plasma-testnet.thematter.io',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        _bytesDispatched: 190,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        allowHalfOpen: false,
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [ClientRequest],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 3625,
        _destroyed: false,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 29,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 625,
        [Symbol(connect-options)]: [Object],
        [Symbol(asyncId)]: 39,
        [Symbol(triggerAsyncId)]: 37 },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'plasma-testnet.thematter.io',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'plasma-testnet.thematter.io',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        _bytesDispatched: 190,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        allowHalfOpen: false,
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [ClientRequest],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 3625,
        _destroyed: false,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 29,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 625,
        [Symbol(connect-options)]: [Object],
        [Symbol(asyncId)]: 39,
        [Symbol(triggerAsyncId)]: 37 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { date: 'Fri, 23 Nov 2018 13:25:19 GMT',
        'content-type': 'text/html',
        'transfer-encoding': 'chunked',
        connection: 'close',
        'set-cookie': [Array],
        'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        server: 'cloudflare',
        'cf-ray': '47e3f60dfa6697f2-FRA' },
     rawHeaders:
      [ 'Date',
        'Fri, 23 Nov 2018 13:25:19 GMT',
        'Content-Type',
        'text/html',
        'Transfer-Encoding',
        'chunked',
        'Connection',
        'close',
        'Set-Cookie',
        '__cfduid=d5e74246815c5d6ec4267b836daffa66d1542979519; expires=Sat, 23-Nov-19 13:25:19 GMT; path=/; domain=.thematter.io; HttpOnly; Secure',
        'Expect-CT',
        'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        'Server',
        'cloudflare',
        'CF-RAY',
        '47e3f60dfa6697f2-FRA' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'plasma-testnet.thematter.io',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'plasma-testnet.thematter.io',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        _bytesDispatched: 190,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        allowHalfOpen: false,
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [ClientRequest],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 3625,
        _destroyed: false,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 29,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(bytesRead)]: 625,
        [Symbol(connect-options)]: [Object],
        [Symbol(asyncId)]: 39,
        [Symbol(triggerAsyncId)]: 37 },
     _consuming: true,
     _dumped: false,
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header: 'GET /api/v1/lastWrittenBlock HTTP/1.1\r\naccept: application/json\r\nreferer: http://plasma-testnet.thematter.io/api/v1/lastWrittenBlock\r\nhost: plasma-testnet.thematter.io\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/api/v1/lastWrittenBlock',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'GET',
        uri: [Url],
        timeout: 30000,
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Promise],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        headers: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'plasma-testnet.thematter.io',
        path: '/api/v1/lastWrittenBlock',
        _json: true,
        httpModule: [Object],
        agentClass: [Function],
        href: 'https://plasma-testnet.thematter.io/api/v1/lastWrittenBlock',
        ntick: true,
        timeoutTimer: null,
        response: [Circular],
        originalHost: 'plasma-testnet.thematter.io',
        originalHostHeaderName: 'host',
        agent: [Agent],
        _started: true,
        req: [ClientRequest],
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: '<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n' } }

`env` files weren't changed, neither *config.js*
